In [1]:
import numpy as np
import fasttext
from collections import defaultdict
from pycountry import languages
import pickle

/home/weiwya/essex-graphs/venv/lib/python3.6/site-packages/sklearn/utils/deprecation.py:143: FutureWarning: The sklearn.ensemble.forest module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.ensemble. Anything that cannot be imported from sklearn.ensemble is now part of the private API.
  warnings.warn(message, FutureWarning)


In [3]:
def parse_language_data(file_name):
    labels, sentences = [],[]
    with open(file_name) as handle:
        for line in handle.readlines():
            ll = line.split()
            labels.append(ll[0])
            sentences.append(" ".join(ll[1:]))
                             
    print( len(labels), len(sentences))
    return labels, sentences
        

In [4]:
fast_text_emb = fasttext.load_model('../language_detection/data/langdetect_unsuperised.bin')
data_file = '../language_detection/data/all.txt'

data_labels, data_sentences = parse_language_data(data_file)

8194317 8194317


In [1]:
from collections import Counter
allLang = Counter(data_labels)
print (len(allLang))



wanted_language = set(['eng', 'cmn', 'jpn', 'spa', 'fra',
                       'deu', 'swe', 'nob', 'dan', 'nld', 
                       'heb', 'ara', 'rus', 'ukr', 'pol',
                       'kor', 'hrv', 'srp', 'vie', 'bos',
                       'fin', 'est', 'cat', 'hun', 'bre', 
                       'hin', 'yue', 'wuu', 'ita', 'por'])

#break into random batch of 3
data_dict = defaultdict(list)
for l, s in zip(data_labels, data_sentences):
    l = l.split('__')[-1]
    if l in wanted_language:
        data_dict[l].append(fast_text_emb.get_sentence_vector(s))

for k, v in data_dict.items():
    k = languages.get(alpha_3 =k).name
    print(k, "\t\t", len(v))

print (len(wanted_language))

NameError: name 'data_labels' is not defined

In [7]:
#index classes
label_to_idx = {l:i for i, l in enumerate(wanted_language)}
idx_to_label = {label_to_idx[l]:l for l in wanted_language}
   

# #org by closes language
classes = np.array([    
    
    [label_to_idx['swe'], label_to_idx['nob'], label_to_idx['dan']  ],

    [label_to_idx['cmn'], label_to_idx['yue'], label_to_idx['wuu']  ],
    
    [label_to_idx['rus'], label_to_idx['ukr'], label_to_idx['pol']  ],
    
    [label_to_idx['spa'], label_to_idx['ita'], label_to_idx['por']  ],
    
    [label_to_idx['fin'], label_to_idx['hun'], label_to_idx['est']  ],
    
    [label_to_idx['eng'], label_to_idx['nld'], label_to_idx['deu']  ],
    
    [label_to_idx['hrv'], label_to_idx['srp'], label_to_idx['bos']  ],
    
    [label_to_idx['jpn'], label_to_idx['kor'], label_to_idx['vie']  ],
    
    [label_to_idx['heb'], label_to_idx['ara'], label_to_idx['hin']  ],
    
    [label_to_idx['fra'], label_to_idx['cat'], label_to_idx['bre']  ],
      
])




for i in range(classes.shape[0]):
    print ([languages.get(alpha_3=idx_to_label[x]).name for x in classes[i]] )

['Swedish', 'Norwegian Bokmål', 'Danish']
['Mandarin Chinese', 'Yue Chinese', 'Wu Chinese']
['Russian', 'Ukrainian', 'Polish']
['Spanish', 'Italian', 'Portuguese']
['Finnish', 'Hungarian', 'Estonian']
['English', 'Dutch', 'German']
['Croatian', 'Serbian', 'Bosnian']
['Japanese', 'Korean', 'Vietnamese']
['Hebrew', 'Arabic', 'Hindi']
['French', 'Catalan', 'Breton']


In [8]:
#data_dict contains all 

[array([ 0.06384033,  0.09807517,  0.10140504, -0.04802534,  0.4456838 ,
        -0.16663755,  0.24801932, -0.3035355 ,  0.31449816, -0.17992453,
        -0.08542453, -0.04634124, -0.29623422, -0.01492423,  0.18772891,
        -0.292852  ], dtype=float32),
 array([ 0.03376766, -0.09098874,  0.10372527,  0.01854615,  0.3691    ,
        -0.4231505 ,  0.14813262, -0.17749694,  0.30851626, -0.24311773,
         0.00478562, -0.1707206 , -0.28650647,  0.24584329,  0.16266997,
        -0.36355716], dtype=float32),
 array([ 0.0694203 , -0.0855913 ,  0.16364191,  0.02331613,  0.40883932,
        -0.23317395,  0.19221233, -0.20835829,  0.3953352 , -0.11435249,
        -0.00877086, -0.24142645, -0.354021  ,  0.22605932,  0.11343932,
        -0.32084394], dtype=float32),
 array([ 0.1545732 ,  0.05085606,  0.17992827,  0.0111843 ,  0.40182495,
        -0.23303239,  0.15305227, -0.3361965 ,  0.36961973, -0.17691009,
         0.04272006, -0.13207681, -0.33889303,  0.11109174,  0.09169595,
        -0